/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface DvHeader {}
  interface DvHeaderAttributes extends StencilHTMLAttributes {}

  interface DvPokedexDisplay {
    'isPokemonLoading': boolean;
    'pokemon': any;
    'species': any;
  }
  interface DvPokedexDisplayAttributes extends StencilHTMLAttributes {
    'isPokemonLoading'?: boolean;
    'pokemon'?: any;
    'species'?: any;
  }

  interface DvGallery {
    'imgSources': any;
  }
  interface DvGalleryAttributes extends StencilHTMLAttributes {
    'imgSources'?: any;
  }

  interface DvLoadMore {
    'handleFetchMore': any;
  }
  interface DvLoadMoreAttributes extends StencilHTMLAttributes {
    'handleFetchMore'?: any;
  }

  interface DvPokedexPage {}
  interface DvPokedexPageAttributes extends StencilHTMLAttributes {}

  interface DvPokemonInfo {
    'isPokemonLoading': any;
    'pokemon': any;
    'species': any;
  }
  interface DvPokemonInfoAttributes extends StencilHTMLAttributes {
    'isPokemonLoading'?: any;
    'pokemon'?: any;
    'species'?: any;
  }

  interface DvPokemonListControls {
    'handleButtonClick': any;
    'handleInputChange': any;
    'isListCollapsed': boolean;
    'searchTerm': string;
  }
  interface DvPokemonListControlsAttributes extends StencilHTMLAttributes {
    'handleButtonClick'?: any;
    'handleInputChange'?: any;
    'isListCollapsed'?: boolean;
    'searchTerm'?: string;
  }

  interface DvPokemonList {
    'handleFetchMore': any;
    'handlePokemonClick': any;
    'pokeData': any;
  }
  interface DvPokemonListAttributes extends StencilHTMLAttributes {
    'handleFetchMore'?: any;
    'handlePokemonClick'?: any;
    'pokeData'?: any;
  }

  interface DvPokemonMoves {
    'pokemon': any;
  }
  interface DvPokemonMovesAttributes extends StencilHTMLAttributes {
    'pokemon'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'DvHeader': Components.DvHeader;
    'DvPokedexDisplay': Components.DvPokedexDisplay;
    'DvGallery': Components.DvGallery;
    'DvLoadMore': Components.DvLoadMore;
    'DvPokedexPage': Components.DvPokedexPage;
    'DvPokemonInfo': Components.DvPokemonInfo;
    'DvPokemonListControls': Components.DvPokemonListControls;
    'DvPokemonList': Components.DvPokemonList;
    'DvPokemonMoves': Components.DvPokemonMoves;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'dv-header': Components.DvHeaderAttributes;
    'dv-pokedex-display': Components.DvPokedexDisplayAttributes;
    'dv-gallery': Components.DvGalleryAttributes;
    'dv-load-more': Components.DvLoadMoreAttributes;
    'dv-pokedex-page': Components.DvPokedexPageAttributes;
    'dv-pokemon-info': Components.DvPokemonInfoAttributes;
    'dv-pokemon-list-controls': Components.DvPokemonListControlsAttributes;
    'dv-pokemon-list': Components.DvPokemonListAttributes;
    'dv-pokemon-moves': Components.DvPokemonMovesAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLDvHeaderElement extends Components.DvHeader, HTMLStencilElement {}
  var HTMLDvHeaderElement: {
    prototype: HTMLDvHeaderElement;
    new (): HTMLDvHeaderElement;
  };

  interface HTMLDvPokedexDisplayElement extends Components.DvPokedexDisplay, HTMLStencilElement {}
  var HTMLDvPokedexDisplayElement: {
    prototype: HTMLDvPokedexDisplayElement;
    new (): HTMLDvPokedexDisplayElement;
  };

  interface HTMLDvGalleryElement extends Components.DvGallery, HTMLStencilElement {}
  var HTMLDvGalleryElement: {
    prototype: HTMLDvGalleryElement;
    new (): HTMLDvGalleryElement;
  };

  interface HTMLDvLoadMoreElement extends Components.DvLoadMore, HTMLStencilElement {}
  var HTMLDvLoadMoreElement: {
    prototype: HTMLDvLoadMoreElement;
    new (): HTMLDvLoadMoreElement;
  };

  interface HTMLDvPokedexPageElement extends Components.DvPokedexPage, HTMLStencilElement {}
  var HTMLDvPokedexPageElement: {
    prototype: HTMLDvPokedexPageElement;
    new (): HTMLDvPokedexPageElement;
  };

  interface HTMLDvPokemonInfoElement extends Components.DvPokemonInfo, HTMLStencilElement {}
  var HTMLDvPokemonInfoElement: {
    prototype: HTMLDvPokemonInfoElement;
    new (): HTMLDvPokemonInfoElement;
  };

  interface HTMLDvPokemonListControlsElement extends Components.DvPokemonListControls, HTMLStencilElement {}
  var HTMLDvPokemonListControlsElement: {
    prototype: HTMLDvPokemonListControlsElement;
    new (): HTMLDvPokemonListControlsElement;
  };

  interface HTMLDvPokemonListElement extends Components.DvPokemonList, HTMLStencilElement {}
  var HTMLDvPokemonListElement: {
    prototype: HTMLDvPokemonListElement;
    new (): HTMLDvPokemonListElement;
  };

  interface HTMLDvPokemonMovesElement extends Components.DvPokemonMoves, HTMLStencilElement {}
  var HTMLDvPokemonMovesElement: {
    prototype: HTMLDvPokemonMovesElement;
    new (): HTMLDvPokemonMovesElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'dv-header': HTMLDvHeaderElement
    'dv-pokedex-display': HTMLDvPokedexDisplayElement
    'dv-gallery': HTMLDvGalleryElement
    'dv-load-more': HTMLDvLoadMoreElement
    'dv-pokedex-page': HTMLDvPokedexPageElement
    'dv-pokemon-info': HTMLDvPokemonInfoElement
    'dv-pokemon-list-controls': HTMLDvPokemonListControlsElement
    'dv-pokemon-list': HTMLDvPokemonListElement
    'dv-pokemon-moves': HTMLDvPokemonMovesElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'dv-header': HTMLDvHeaderElement;
    'dv-pokedex-display': HTMLDvPokedexDisplayElement;
    'dv-gallery': HTMLDvGalleryElement;
    'dv-load-more': HTMLDvLoadMoreElement;
    'dv-pokedex-page': HTMLDvPokedexPageElement;
    'dv-pokemon-info': HTMLDvPokemonInfoElement;
    'dv-pokemon-list-controls': HTMLDvPokemonListControlsElement;
    'dv-pokemon-list': HTMLDvPokemonListElement;
    'dv-pokemon-moves': HTMLDvPokemonMovesElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
